# Generated by Django 2.0.7 on 2018-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
