# Generated by Django 2.0.7 on 2019-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_effect_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='id',
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
