# Generated by Django 2.0.7 on 2019-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190610_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
